"use client";

import { useQuery } from "@tanstack/react-query";
import { useMemo } from "react";
import { useI18n } from "@/components/providers/I18nProvider";
import type { ExerciseTranslation } from "@/lib/exercise-translate";

/**
 * Exercise translations are shipped as a bundled static asset
 * (`public/exercise-translations.json`, generated by
 * `scripts/export-translations.mjs` from PocketBase). Reading from the bundle
 * instead of querying PocketBase means:
 *   • no auth gate — logged-out / guest users get ru/uz too, and
 *   • no per-view network round-trip (one cached fetch for the whole catalog).
 *
 * The bundle carries `en` overlays too — sparse rows holding only the fields the
 * source dataset left empty (generated during seeding). The field-level `||`
 * fallback in `applyTranslationToLibraryExercise` makes applying a sparse `en`
 * overlay safe (real API values win; generated values fill the gaps).
 */

type LocaleMap = Record<string, ExerciseTranslation>;
// `nameIndex` maps normalize(English name) → exerciseExtId. The bundle is keyed
// by the exercises.json id space ("1000"), but the live library loads from the
// ExerciseDB fork API whose ids are different hashes ("VPPtusI"). The English
// name is the only shared key, so callers resolve fork exercises → extId by name.
type Bundle = { en: LocaleMap; ru: LocaleMap; uz: LocaleMap; nameIndex?: Record<string, string> };

const EMPTY: Bundle = { en: {}, ru: {}, uz: {} };

const normalizeName = (s: string | undefined): string =>
  (s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");

/** Load + cache the bundle once for the whole session. */
function useTranslationBundle(): Bundle {
  const { data } = useQuery<Bundle>({
    queryKey: ["exercise-translations-bundle"],
    staleTime: Infinity,
    gcTime: Infinity,
    queryFn: async () => {
      try {
        const res = await fetch("/exercise-translations.json");
        if (!res.ok) return EMPTY;
        return (await res.json()) as Bundle;
      } catch {
        return EMPTY;
      }
    },
  });
  return data ?? EMPTY;
}

function localeMap(bundle: Bundle, language: string): LocaleMap {
  return (bundle as unknown as Record<string, LocaleMap>)[language] ?? {};
}

/**
 * Resolver: fork-API exercise (or any exercise with an English name) → the
 * bundle's exerciseExtId, via the normalized-name index. Use this to bridge the
 * live library's id space to the translation bundle's id space.
 */
export function useExerciseExtIdResolver(): (name: string) => string | undefined {
  const bundle = useTranslationBundle();
  return useMemo(() => {
    const index = bundle.nameIndex ?? {};
    return (name: string) => index[normalizeName(name)];
  }, [bundle]);
}

/** Single translation by (exerciseExtId, active language). */
export function useExerciseTranslation(exerciseExtId: string | undefined): {
  data: ExerciseTranslation | null;
} {
  const { language } = useI18n();
  const bundle = useTranslationBundle();
  const data = useMemo<ExerciseTranslation | null>(() => {
    if (!exerciseExtId) return null;
    return localeMap(bundle, language)[exerciseExtId] ?? null;
  }, [bundle, language, exerciseExtId]);
  return { data };
}

/** Batch lookup for a list of exerciseExtIds, keyed by exerciseExtId. */
export function useExercisesBatchTranslation(
  exerciseExtIds: string[],
): { data: Map<string, ExerciseTranslation>; isLoading: boolean } {
  const { language } = useI18n();
  const bundle = useTranslationBundle();
  const key = exerciseExtIds.join(",");
  const data = useMemo(() => {
    const map = new Map<string, ExerciseTranslation>();
    const lm = localeMap(bundle, language);
    for (const id of exerciseExtIds) {
      const t = lm[id];
      if (t) map.set(id, t);
    }
    return map;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bundle, language, key]);
  return { data, isLoading: false };
}

/**
 * All translated exercise names for the active language (powers multilingual
 * search). Returns an empty map for `en` (the bundle's en overlay never carries
 * a `name` — English names come straight from the catalog API).
 */
export function useAllExerciseTranslationNames(): Map<string, string> {
  const { language } = useI18n();
  const bundle = useTranslationBundle();
  return useMemo(() => {
    const map = new Map<string, string>();
    for (const [id, t] of Object.entries(localeMap(bundle, language))) {
      if (t.name) map.set(id, t.name);
    }
    return map;
  }, [bundle, language]);
}
